version: '3'
services:
  #Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hris-app-frontend
    restart: unless-stopped
    tty: true
    ports:
      - "80:3000"
    networks:
      - hris
  
  #PHP Service
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: hris-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./backend/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - hris

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: hris-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./backend/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - hris

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: hris-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: human_resource_website
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - hris

#Docker Networks
networks:
  hris:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
